defmodule Salamendar.Schema do
  @moduledoc """
  Base for every Ecto schema in Salamendar: `use Salamendar.Schema` in place
  of `use Ecto.Schema`.

  Primary keys are time-ordered UUIDv7s generated by Ecto (better index
  locality than random v4s), foreign keys are UUIDs, and timestamps are
  `utc_datetime_usec`. These match the repo's `migration_*` config.
  """

  defmacro __using__(_opts) do
    quote do
      use Ecto.Schema

      @primary_key {:id, Ecto.UUID, autogenerate: [version: 7]}
      @foreign_key_type Ecto.UUID
      @timestamps_opts [type: :utc_datetime_usec]
    end
  end
end
